apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sharelatex-ingress
  namespace: overleaf
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
    - host: latex.pasuko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sharelatex
                port:
                  number: 80