apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp
resources:
  - core/configmap.yaml
  - core/deployment.yaml
  - core/service.yaml
  - core/redis.yaml
  - core/postgres-service.yaml
  - core/postgres-statefulset.yaml
  - extras/admin-mw.yaml
  - extras/admin-ingress.yaml
  - extras/ingress.yaml
