apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp
resources:
  - core/configmap.yaml
  - core/deployment.yaml
  - core/service.yaml
  - core/redis.yaml
  - core/ingress.yaml
