apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcpgateway-api
  namespace: mcp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: mcp.pasuko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcpgateway
                port:
                  number: 80
