apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crawl4ai
  namespace: crawl4ai
spec:
  ingressClassName: traefik
  rules:
    - host: crawl4ai.pasuko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crawl4ai
                port:
                  number: 80
